server:
  port: 6661

spring:
  application:
    name: java-spring-boot-sql2o-rest-crud
  threads:
    virtual:
      enabled: true
  datasource:
    url: jdbc:mysql://${MYSQL_DOCKER_HOST:localhost}:${MYSQL_DOCKER_PORT:3306}/${MYSQL_DOCKER_DATABASE:java-spring-boot-sql2o-rest-crud}?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC
    username: ${MYSQL_DOCKER_USERNAME:root}
    password: ${MYSQL_DOCKER_PASSWORD:root}
    driver-class-name: com.mysql.cj.jdbc.Driver
    hikari:
      pool-name: HikariPool-1
      maximum-pool-size: 30
      throttle-percentage: 98
      minimum-idle: 5
      idle-timeout: 300000
      max-lifetime: 1800000
      connection-timeout: 30000
      leak-detection-threshold: 60000
  flyway:
    enabled: true
    baseline-on-migrate: true
    locations: classpath:db/migration
    validate-on-migrate: true
  jackson:
    default-property-inclusion: non_null

logging:
  config: classpath:logback-spring.xml
